### ISSUE TITLE
renderReact not works

### ISSUE THREAD

**Issue by k4mr4n** [airbnb/hypernova-react#43] opened 2018-04-17 14:52 UTC
Hey all

```
<div id="root">{{ html }}</div>
```

If hypernova server fails by any reason and the html content would be empty, then the `renderReact('Component', Component)` wouldn't work either returns blank page and I have to call:
```
ReactDOM.hydrate(
    <Component />,
    document.getElementById('root')
  )
```
In this case how could I know my root is empty? because this condition throws error due to undefined document object:
`document.getElementById('root') !== null && document.getElementById('root').hasChildNodes()`
```
TypeError: ((!(null === document.getElementById(...))) && document.getElementById(...).hasChildNodes(...)) is not a function
```

**Comment by ljharb** [comment] 2018-04-17 16:38
This seems like a duplicate of https://github.com/airbnb/hypernova/issues/115

**Comment by k4mr4n** [comment] 2018-04-17 16:58
@ljharb yes no one there answered and I thought its concern with this repo too
so I clone it here!
and what do you think about it?

**Comment by k4mr4n** [comment] 2018-04-20 15:40
@ljharb I fixed it with if-else in my code that's why I closed it
and in the first place my if-else had a syntax problem that's why I was getting TypeError 😞

**Comment by ljharb** [comment] 2018-04-20 20:30
Thanks for clarifying :-)

**Closed by ljharb** 2018-04-20 20:30 UTC

**Comment by kstratis** [comment] 2020-04-11 13:41
My apologies for resurrecting the dead but why would someone have to manually check whether the server  failed to render or not..?

reactRender should have been able to figure that out from the data keys... right?
